apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  labels:
    app: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      imagePullSecrets:
        - name: registry-creds
      containers:
        - name: api-gateway
          imagePullPolicy: Always
          image: {{ .Values.image }}
          env:
            - name: USER_SERVICE_GRAPHQL
              value: {{ .Values.federation.services.user }}
            - name: CONTRY_SERVICE_GRAPHQL
              value: {{ .Values.federation.services.contry }}
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
  ports:
    - port: 4000
      targetPort: 4000
      name: api-gateway
  selector:
    app: api-gateway
